#!/bin/sh

# Aktualisiert das "run"-Skript und führt es aus

DIR="$HOME/.vorkurs"
DIRDIR="$DIR/run" # So that "run" doesn't end up in our PATH
FILE="$DIRDIR"/run

mkdir -p "$DIRDIR"
wget -q tubs-ips.github.io/nutsh-vorkurs/run -O "$FILE"
chmod u+x "$FILE"
exec "$FILE"
